### PR TITLE
Add a script for general text analysis

### PR DESCRIPTION
**Pull request by essencious**
New script to analyse unique word and character count of a piece of text, and optionally output all words and characters to a .txt file:

Usage:
- `python3 analyzer.py -t "target.txt" -o "output.txt"`

Example output:
```
Total Unique Words: 32226
Total Unique Characters: 3572
```

Example `output.txt`:
```
=== All Unique Words ===
的 : 18840
了 : 15791
昇 : 10683
周 : 9155
余皓 : 8995
我 : 7512
...

=== All Unique Characters ===
的 : 19664
了 : 17135
余 : 14223
皓 : 14103
一 : 12667
周 : 11641
昇 : 10756
不 : 10217
我 : 8723
```

### CODE REVIEW

**Comment by Destaq** [comment]
I assume `comprehension.py` still works as before though, right?

**Comment by essencious** [comment]
> I assume `comprehension.py` still works as before though, right?

Yes I've tested the comprehension.py as well

**Comment by Destaq** [comment]
Will merge on `README.md` update.

**Comment by essencious** [comment]
@Destaq I've updated the readme.

**Review by Destaq — APPROVED** [review]
Looks good.

**Pull request merged**
